version: "3.8"

services:
  app:
    container_name: front-end
    image: front-end
    build:
      context: front-end
      target: development
    depends_on:
      - api
    volumes:
      - "./front-end/src:/app/src"
      - "./front-end/public:/app/public"
    ports:
      - 3000:3000
    networks:
      - empire
  api:
    container_name: back-end
    image: back-end
    build:
      context: back-end
      target: development
    volumes:
      - "./back-end/src:/app/src"
    ports:
      - 3001:3001
    networks:
      - empire
    # workaround around a docker-compose bug when image is also used by docker run (https://github.com/docker/compose/issues/10162)
    # labels:
    #   com.docker.compose.container-number: "1"


networks:
  empire: